// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sessionstore_mock

import (
	"context"

	"github.com/ChewX3D/crypto/internal/app/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionStore creates a new instance of MockSessionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionStore {
	mock := &MockSessionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionStore is an autogenerated mock type for the SessionStore type
type MockSessionStore struct {
	mock.Mock
}

type MockSessionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionStore) EXPECT() *MockSessionStore_Expecter {
	return &MockSessionStore_Expecter{mock: &_m.Mock}
}

// ClearSession provides a mock function for the type MockSessionStore
func (_mock *MockSessionStore) ClearSession(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ClearSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionStore_ClearSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearSession'
type MockSessionStore_ClearSession_Call struct {
	*mock.Call
}

// ClearSession is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSessionStore_Expecter) ClearSession(ctx interface{}) *MockSessionStore_ClearSession_Call {
	return &MockSessionStore_ClearSession_Call{Call: _e.mock.On("ClearSession", ctx)}
}

func (_c *MockSessionStore_ClearSession_Call) Run(run func(ctx context.Context)) *MockSessionStore_ClearSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSessionStore_ClearSession_Call) Return(err error) *MockSessionStore_ClearSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionStore_ClearSession_Call) RunAndReturn(run func(ctx context.Context) error) *MockSessionStore_ClearSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function for the type MockSessionStore
func (_mock *MockSessionStore) GetSession(ctx context.Context) (ports.SessionMetadata, bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 ports.SessionMetadata
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (ports.SessionMetadata, bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) ports.SessionMetadata); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(ports.SessionMetadata)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSessionStore_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockSessionStore_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSessionStore_Expecter) GetSession(ctx interface{}) *MockSessionStore_GetSession_Call {
	return &MockSessionStore_GetSession_Call{Call: _e.mock.On("GetSession", ctx)}
}

func (_c *MockSessionStore_GetSession_Call) Run(run func(ctx context.Context)) *MockSessionStore_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSessionStore_GetSession_Call) Return(sessionMetadata ports.SessionMetadata, b bool, err error) *MockSessionStore_GetSession_Call {
	_c.Call.Return(sessionMetadata, b, err)
	return _c
}

func (_c *MockSessionStore_GetSession_Call) RunAndReturn(run func(ctx context.Context) (ports.SessionMetadata, bool, error)) *MockSessionStore_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// SaveSession provides a mock function for the type MockSessionStore
func (_mock *MockSessionStore) SaveSession(ctx context.Context, session ports.SessionMetadata) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for SaveSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.SessionMetadata) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionStore_SaveSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveSession'
type MockSessionStore_SaveSession_Call struct {
	*mock.Call
}

// SaveSession is a helper method to define mock.On call
//   - ctx context.Context
//   - session ports.SessionMetadata
func (_e *MockSessionStore_Expecter) SaveSession(ctx interface{}, session interface{}) *MockSessionStore_SaveSession_Call {
	return &MockSessionStore_SaveSession_Call{Call: _e.mock.On("SaveSession", ctx, session)}
}

func (_c *MockSessionStore_SaveSession_Call) Run(run func(ctx context.Context, session ports.SessionMetadata)) *MockSessionStore_SaveSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.SessionMetadata
		if args[1] != nil {
			arg1 = args[1].(ports.SessionMetadata)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionStore_SaveSession_Call) Return(err error) *MockSessionStore_SaveSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionStore_SaveSession_Call) RunAndReturn(run func(ctx context.Context, session ports.SessionMetadata) error) *MockSessionStore_SaveSession_Call {
	_c.Call.Return(run)
	return _c
}
