// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package credentialstore_mock

import (
	"context"

	"github.com/ChewX3D/crypto/internal/domain/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCredentialStore creates a new instance of MockCredentialStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialStore {
	mock := &MockCredentialStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCredentialStore is an autogenerated mock type for the CredentialStore type
type MockCredentialStore struct {
	mock.Mock
}

type MockCredentialStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialStore) EXPECT() *MockCredentialStore_Expecter {
	return &MockCredentialStore_Expecter{mock: &_m.Mock}
}

// BackendName provides a mock function for the type MockCredentialStore
func (_mock *MockCredentialStore) BackendName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BackendName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCredentialStore_BackendName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BackendName'
type MockCredentialStore_BackendName_Call struct {
	*mock.Call
}

// BackendName is a helper method to define mock.On call
func (_e *MockCredentialStore_Expecter) BackendName() *MockCredentialStore_BackendName_Call {
	return &MockCredentialStore_BackendName_Call{Call: _e.mock.On("BackendName")}
}

func (_c *MockCredentialStore_BackendName_Call) Run(run func()) *MockCredentialStore_BackendName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCredentialStore_BackendName_Call) Return(s string) *MockCredentialStore_BackendName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCredentialStore_BackendName_Call) RunAndReturn(run func() string) *MockCredentialStore_BackendName_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockCredentialStore
func (_mock *MockCredentialStore) Delete(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCredentialStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCredentialStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCredentialStore_Expecter) Delete(ctx interface{}) *MockCredentialStore_Delete_Call {
	return &MockCredentialStore_Delete_Call{Call: _e.mock.On("Delete", ctx)}
}

func (_c *MockCredentialStore_Delete_Call) Run(run func(ctx context.Context)) *MockCredentialStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCredentialStore_Delete_Call) Return(err error) *MockCredentialStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCredentialStore_Delete_Call) RunAndReturn(run func(ctx context.Context) error) *MockCredentialStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockCredentialStore
func (_mock *MockCredentialStore) Exists(ctx context.Context) (bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCredentialStore_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockCredentialStore_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCredentialStore_Expecter) Exists(ctx interface{}) *MockCredentialStore_Exists_Call {
	return &MockCredentialStore_Exists_Call{Call: _e.mock.On("Exists", ctx)}
}

func (_c *MockCredentialStore_Exists_Call) Run(run func(ctx context.Context)) *MockCredentialStore_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCredentialStore_Exists_Call) Return(b bool, err error) *MockCredentialStore_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockCredentialStore_Exists_Call) RunAndReturn(run func(ctx context.Context) (bool, error)) *MockCredentialStore_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type MockCredentialStore
func (_mock *MockCredentialStore) Load(ctx context.Context) (auth.Credential, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 auth.Credential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (auth.Credential, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) auth.Credential); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(auth.Credential)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCredentialStore_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockCredentialStore_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCredentialStore_Expecter) Load(ctx interface{}) *MockCredentialStore_Load_Call {
	return &MockCredentialStore_Load_Call{Call: _e.mock.On("Load", ctx)}
}

func (_c *MockCredentialStore_Load_Call) Run(run func(ctx context.Context)) *MockCredentialStore_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCredentialStore_Load_Call) Return(credential auth.Credential, err error) *MockCredentialStore_Load_Call {
	_c.Call.Return(credential, err)
	return _c
}

func (_c *MockCredentialStore_Load_Call) RunAndReturn(run func(ctx context.Context) (auth.Credential, error)) *MockCredentialStore_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockCredentialStore
func (_mock *MockCredentialStore) Save(ctx context.Context, credential auth.Credential) error {
	ret := _mock.Called(ctx, credential)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.Credential) error); ok {
		r0 = returnFunc(ctx, credential)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCredentialStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockCredentialStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - credential auth.Credential
func (_e *MockCredentialStore_Expecter) Save(ctx interface{}, credential interface{}) *MockCredentialStore_Save_Call {
	return &MockCredentialStore_Save_Call{Call: _e.mock.On("Save", ctx, credential)}
}

func (_c *MockCredentialStore_Save_Call) Run(run func(ctx context.Context, credential auth.Credential)) *MockCredentialStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.Credential
		if args[1] != nil {
			arg1 = args[1].(auth.Credential)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCredentialStore_Save_Call) Return(err error) *MockCredentialStore_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCredentialStore_Save_Call) RunAndReturn(run func(ctx context.Context, credential auth.Credential) error) *MockCredentialStore_Save_Call {
	_c.Call.Return(run)
	return _c
}
