// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package noncesource_mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockNonceSource creates a new instance of MockNonceSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNonceSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNonceSource {
	mock := &MockNonceSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNonceSource is an autogenerated mock type for the NonceSource type
type MockNonceSource struct {
	mock.Mock
}

type MockNonceSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNonceSource) EXPECT() *MockNonceSource_Expecter {
	return &MockNonceSource_Expecter{mock: &_m.Mock}
}

// Next provides a mock function for the type MockNonceSource
func (_mock *MockNonceSource) Next() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockNonceSource_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockNonceSource_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *MockNonceSource_Expecter) Next() *MockNonceSource_Next_Call {
	return &MockNonceSource_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *MockNonceSource_Next_Call) Run(run func()) *MockNonceSource_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNonceSource_Next_Call) Return(n int64) *MockNonceSource_Next_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockNonceSource_Next_Call) RunAndReturn(run func() int64) *MockNonceSource_Next_Call {
	_c.Call.Return(run)
	return _c
}
