// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package collateralorderexecutor_mock

import (
	"context"
	"encoding/json"

	"github.com/ChewX3D/crypto/internal/app/ports"
	"github.com/ChewX3D/crypto/internal/domain/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCollateralOrderExecutor creates a new instance of MockCollateralOrderExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCollateralOrderExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCollateralOrderExecutor {
	mock := &MockCollateralOrderExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCollateralOrderExecutor is an autogenerated mock type for the CollateralOrderExecutor type
type MockCollateralOrderExecutor struct {
	mock.Mock
}

type MockCollateralOrderExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCollateralOrderExecutor) EXPECT() *MockCollateralOrderExecutor_Expecter {
	return &MockCollateralOrderExecutor_Expecter{mock: &_m.Mock}
}

// GetCollateralAccountHedgeMode provides a mock function for the type MockCollateralOrderExecutor
func (_mock *MockCollateralOrderExecutor) GetCollateralAccountHedgeMode(ctx context.Context, credential auth.Credential) (bool, error) {
	ret := _mock.Called(ctx, credential)

	if len(ret) == 0 {
		panic("no return value specified for GetCollateralAccountHedgeMode")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.Credential) (bool, error)); ok {
		return returnFunc(ctx, credential)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.Credential) bool); ok {
		r0 = returnFunc(ctx, credential)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth.Credential) error); ok {
		r1 = returnFunc(ctx, credential)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollateralOrderExecutor_GetCollateralAccountHedgeMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCollateralAccountHedgeMode'
type MockCollateralOrderExecutor_GetCollateralAccountHedgeMode_Call struct {
	*mock.Call
}

// GetCollateralAccountHedgeMode is a helper method to define mock.On call
//   - ctx context.Context
//   - credential auth.Credential
func (_e *MockCollateralOrderExecutor_Expecter) GetCollateralAccountHedgeMode(ctx interface{}, credential interface{}) *MockCollateralOrderExecutor_GetCollateralAccountHedgeMode_Call {
	return &MockCollateralOrderExecutor_GetCollateralAccountHedgeMode_Call{Call: _e.mock.On("GetCollateralAccountHedgeMode", ctx, credential)}
}

func (_c *MockCollateralOrderExecutor_GetCollateralAccountHedgeMode_Call) Run(run func(ctx context.Context, credential auth.Credential)) *MockCollateralOrderExecutor_GetCollateralAccountHedgeMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.Credential
		if args[1] != nil {
			arg1 = args[1].(auth.Credential)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCollateralOrderExecutor_GetCollateralAccountHedgeMode_Call) Return(b bool, err error) *MockCollateralOrderExecutor_GetCollateralAccountHedgeMode_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockCollateralOrderExecutor_GetCollateralAccountHedgeMode_Call) RunAndReturn(run func(ctx context.Context, credential auth.Credential) (bool, error)) *MockCollateralOrderExecutor_GetCollateralAccountHedgeMode_Call {
	_c.Call.Return(run)
	return _c
}

// PlaceCollateralLimitOrder provides a mock function for the type MockCollateralOrderExecutor
func (_mock *MockCollateralOrderExecutor) PlaceCollateralLimitOrder(ctx context.Context, credential auth.Credential, request ports.CollateralLimitOrderRequest) (json.RawMessage, error) {
	ret := _mock.Called(ctx, credential, request)

	if len(ret) == 0 {
		panic("no return value specified for PlaceCollateralLimitOrder")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.Credential, ports.CollateralLimitOrderRequest) (json.RawMessage, error)); ok {
		return returnFunc(ctx, credential, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.Credential, ports.CollateralLimitOrderRequest) json.RawMessage); ok {
		r0 = returnFunc(ctx, credential, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth.Credential, ports.CollateralLimitOrderRequest) error); ok {
		r1 = returnFunc(ctx, credential, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollateralOrderExecutor_PlaceCollateralLimitOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlaceCollateralLimitOrder'
type MockCollateralOrderExecutor_PlaceCollateralLimitOrder_Call struct {
	*mock.Call
}

// PlaceCollateralLimitOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - credential auth.Credential
//   - request ports.CollateralLimitOrderRequest
func (_e *MockCollateralOrderExecutor_Expecter) PlaceCollateralLimitOrder(ctx interface{}, credential interface{}, request interface{}) *MockCollateralOrderExecutor_PlaceCollateralLimitOrder_Call {
	return &MockCollateralOrderExecutor_PlaceCollateralLimitOrder_Call{Call: _e.mock.On("PlaceCollateralLimitOrder", ctx, credential, request)}
}

func (_c *MockCollateralOrderExecutor_PlaceCollateralLimitOrder_Call) Run(run func(ctx context.Context, credential auth.Credential, request ports.CollateralLimitOrderRequest)) *MockCollateralOrderExecutor_PlaceCollateralLimitOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.Credential
		if args[1] != nil {
			arg1 = args[1].(auth.Credential)
		}
		var arg2 ports.CollateralLimitOrderRequest
		if args[2] != nil {
			arg2 = args[2].(ports.CollateralLimitOrderRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCollateralOrderExecutor_PlaceCollateralLimitOrder_Call) Return(rawMessage json.RawMessage, err error) *MockCollateralOrderExecutor_PlaceCollateralLimitOrder_Call {
	_c.Call.Return(rawMessage, err)
	return _c
}

func (_c *MockCollateralOrderExecutor_PlaceCollateralLimitOrder_Call) RunAndReturn(run func(ctx context.Context, credential auth.Credential, request ports.CollateralLimitOrderRequest) (json.RawMessage, error)) *MockCollateralOrderExecutor_PlaceCollateralLimitOrder_Call {
	_c.Call.Return(run)
	return _c
}
