// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authusecases_mock

import (
	"context"

	"github.com/ChewX3D/crypto/internal/app/services/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthUseCases creates a new instance of MockAuthUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthUseCases {
	mock := &MockAuthUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthUseCases is an autogenerated mock type for the AuthUseCases type
type MockAuthUseCases struct {
	mock.Mock
}

type MockAuthUseCases_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthUseCases) EXPECT() *MockAuthUseCases_Expecter {
	return &MockAuthUseCases_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockAuthUseCases
func (_mock *MockAuthUseCases) Login(ctx context.Context, request auth.LoginRequest) (auth.LoginResult, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 auth.LoginResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.LoginRequest) (auth.LoginResult, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.LoginRequest) auth.LoginResult); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(auth.LoginResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth.LoginRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUseCases_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthUseCases_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - request auth.LoginRequest
func (_e *MockAuthUseCases_Expecter) Login(ctx interface{}, request interface{}) *MockAuthUseCases_Login_Call {
	return &MockAuthUseCases_Login_Call{Call: _e.mock.On("Login", ctx, request)}
}

func (_c *MockAuthUseCases_Login_Call) Run(run func(ctx context.Context, request auth.LoginRequest)) *MockAuthUseCases_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.LoginRequest
		if args[1] != nil {
			arg1 = args[1].(auth.LoginRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUseCases_Login_Call) Return(loginResult auth.LoginResult, err error) *MockAuthUseCases_Login_Call {
	_c.Call.Return(loginResult, err)
	return _c
}

func (_c *MockAuthUseCases_Login_Call) RunAndReturn(run func(ctx context.Context, request auth.LoginRequest) (auth.LoginResult, error)) *MockAuthUseCases_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockAuthUseCases
func (_mock *MockAuthUseCases) Logout(ctx context.Context) (auth.LogoutResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 auth.LogoutResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (auth.LogoutResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) auth.LogoutResult); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(auth.LogoutResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUseCases_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthUseCases_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuthUseCases_Expecter) Logout(ctx interface{}) *MockAuthUseCases_Logout_Call {
	return &MockAuthUseCases_Logout_Call{Call: _e.mock.On("Logout", ctx)}
}

func (_c *MockAuthUseCases_Logout_Call) Run(run func(ctx context.Context)) *MockAuthUseCases_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthUseCases_Logout_Call) Return(logoutResult auth.LogoutResult, err error) *MockAuthUseCases_Logout_Call {
	_c.Call.Return(logoutResult, err)
	return _c
}

func (_c *MockAuthUseCases_Logout_Call) RunAndReturn(run func(ctx context.Context) (auth.LogoutResult, error)) *MockAuthUseCases_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockAuthUseCases
func (_mock *MockAuthUseCases) Status(ctx context.Context) (auth.StatusResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 auth.StatusResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (auth.StatusResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) auth.StatusResult); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(auth.StatusResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUseCases_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockAuthUseCases_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuthUseCases_Expecter) Status(ctx interface{}) *MockAuthUseCases_Status_Call {
	return &MockAuthUseCases_Status_Call{Call: _e.mock.On("Status", ctx)}
}

func (_c *MockAuthUseCases_Status_Call) Run(run func(ctx context.Context)) *MockAuthUseCases_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthUseCases_Status_Call) Return(statusResult auth.StatusResult, err error) *MockAuthUseCases_Status_Call {
	_c.Call.Return(statusResult, err)
	return _c
}

func (_c *MockAuthUseCases_Status_Call) RunAndReturn(run func(ctx context.Context) (auth.StatusResult, error)) *MockAuthUseCases_Status_Call {
	_c.Call.Return(run)
	return _c
}
