// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package collateralusecases_mock

import (
	"context"

	"github.com/ChewX3D/crypto/internal/app/services/collateral"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCollateralUseCases creates a new instance of MockCollateralUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCollateralUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCollateralUseCases {
	mock := &MockCollateralUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCollateralUseCases is an autogenerated mock type for the CollateralUseCases type
type MockCollateralUseCases struct {
	mock.Mock
}

type MockCollateralUseCases_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCollateralUseCases) EXPECT() *MockCollateralUseCases_Expecter {
	return &MockCollateralUseCases_Expecter{mock: &_m.Mock}
}

// PlaceOrder provides a mock function for the type MockCollateralUseCases
func (_mock *MockCollateralUseCases) PlaceOrder(ctx context.Context, request collateral.PlaceOrderRequest) (collateral.PlaceOrderResult, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for PlaceOrder")
	}

	var r0 collateral.PlaceOrderResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, collateral.PlaceOrderRequest) (collateral.PlaceOrderResult, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, collateral.PlaceOrderRequest) collateral.PlaceOrderResult); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(collateral.PlaceOrderResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, collateral.PlaceOrderRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollateralUseCases_PlaceOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlaceOrder'
type MockCollateralUseCases_PlaceOrder_Call struct {
	*mock.Call
}

// PlaceOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - request collateral.PlaceOrderRequest
func (_e *MockCollateralUseCases_Expecter) PlaceOrder(ctx interface{}, request interface{}) *MockCollateralUseCases_PlaceOrder_Call {
	return &MockCollateralUseCases_PlaceOrder_Call{Call: _e.mock.On("PlaceOrder", ctx, request)}
}

func (_c *MockCollateralUseCases_PlaceOrder_Call) Run(run func(ctx context.Context, request collateral.PlaceOrderRequest)) *MockCollateralUseCases_PlaceOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 collateral.PlaceOrderRequest
		if args[1] != nil {
			arg1 = args[1].(collateral.PlaceOrderRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCollateralUseCases_PlaceOrder_Call) Return(placeOrderResult collateral.PlaceOrderResult, err error) *MockCollateralUseCases_PlaceOrder_Call {
	_c.Call.Return(placeOrderResult, err)
	return _c
}

func (_c *MockCollateralUseCases_PlaceOrder_Call) RunAndReturn(run func(ctx context.Context, request collateral.PlaceOrderRequest) (collateral.PlaceOrderResult, error)) *MockCollateralUseCases_PlaceOrder_Call {
	_c.Call.Return(run)
	return _c
}
